---

- name: Install Windows package "{{ package_name }}" on "{{ inventory_hostname }}"
  win_chocolatey:
   name: "{{ package_name }}"
   params: "{{ parameters }}"
   state: present
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: Start windows service "{{ service_name }}" on "{{ inventory_hostname }}"
  win_service:
   name: "{{ service_name }}"
   state: started
   start_mode: auto
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"
 
- name: Add win_firewall_rule for service "{{ service_name }}" on "{{ inventory_hostname }}"
  win_firewall_rule:
   name: "{{ service_name }}"
   localport: "{{ local_port }}"
   action: allow
   direction: in
   protocol: "{{ protocol_name }}"
   state: present
   enabled: yes
